### ISSUE TITLE
Selecting default kernel to boot

### ISSUE THREAD

**Issue by sebgl** [shvr/fedora-surface-pro-3-kernel#6]
Hi,

Thanks for the custom kernel package, it works fine ! I just installed Fedora 23 on a micro sd card to run with the Surface Pro 3.
I have two questions which are not directly related to your package, but since it seems you are using the same configuration as I am, you might be able to help me.

1) How do you make the newly installed kernel the default one in grub? I saw several instructions on the fedora documentation but it does not seem up to date.
2) When I reboot the SP3 normally it directly boots to the grub. If I want to run Windows I have to remove the sd card first. I expected another behavior: always boot to Windows (sdd) when pressing the Power button, boot to the grub (sd card) when pressing Power button + volume down. How do you use it?

Thanks.

**Comment by lizalc** [comment]
1) That's a problem with `grubby` that other F23 users are having. There are bugs open on the Red Hat bugzilla already, such as https://bugzilla.redhat.com/show_bug.cgi?id=1258716 

2) This is due to the way the SP3 boots from external disks. When you hold the power and volume down buttons to boot it instructs the UEFI to seach for a `bootx64.efi` in the `BOOT` directory on the EFI system partition of an external disk. The `bootx64.efi` that Fedora places in `BOOT` isn't actually GRUB but a shim that will install a UEFI boot entry then load GRUB. It's this UEFI boot entry that causes GRUB to load on later reboots (if you run `efibootmgr` you'll likely see a bunch of "Fedora" entries get listed). There isn't a fix for this. You could try writing a script that deletes the extra boot entry every time you shut down.

My setup is fairly custom, Fedora is installed on my SSD with `/boot` in a BTRFS subvolume and my EFI partition on the SD card. This lets me switch between Windows and Fedora using the key combo at boot but breaks the Fedora tools for updating GRUB (`/boot` in a subvolume isn't officially supported).

**Comment by sebgl** [comment]
Ok, thanks for the detailed information.
I wasn't aware of all the UEFI boot chain. Maybe there's a way to add an extra entry to the grub to chainload Windows (http://askubuntu.com/questions/210914/grub-does-not-show-a-windows-8-option-after-dual-boot).

**Comment by lizalc** [comment]
Looking around more it seems that right now GRUB has no way of chainloading Windows when Secure Boot is enabled. This is actually `shim`'s fault, the utility that gets GRUB working with Secure Boot in the first place.

See these bugs for more info:
https://bugzilla.redhat.com/show_bug.cgi?id=1170245#c24
https://github.com/rhinstaller/shim/issues/42  

Closing this issue since `shim` issues don't apply here.
